language: node_js
sudo: false
node_js:
- '8.9'
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: D7v6LCxHDkUq7T69LvcgCTommR1kOlu/E93IZcLwzgUMBPzaiZpHYyKwj/DNW5dj4RAVkNxsWi8oaZ+pSsZwTb8RJqKwufBV5LqNDL40El9i/my87fPAj4Y7aDDhWeWmCrDcffx0htr9k2eqg9CzVJbkBsJjuHKqdBw/a4CjMaFFNEb2pAf0cB1nt97Tibda7tQYYipDevvLcjuGHHTa9xexqqQTz5VJO6vdU4NyKr37w3ty0oN8Ju+U7PoQYSZETCIEK8PST5rBGBXQdlfXEMgda+WUTAsU6mUKVc+i9tnBoF1yrnvDDgXZqZXwF3jkz1NkuakvzdIQgrrI014dqwcpNA+VRMhcC7lNgWayNucGnvNP/HEWfHbCDxZg+zI9JwdRT66ZTnbazUTxa84xGvRM6iVeyLGjYqf3KNAKCX+kUDryZFnw9mKGARTPz9F/jWiX9lrsfTReeiDeqVld+8Qme5dvvAukeCsWq2+KZtWqxJ2LHv6Fr5o6VzHrRvSFKtnp4N4d0sWXGiLwQ/eEYwS7QitiGfpnnZPDNFHL5/gyv6z9OhPmOJJsoUTsOViys5MM/upFHAZbfeiKMmAxICZIos7MRxnJyOdq7mNrD2zui7O5NSaJtKzDwSStRddWO9TLO0dFN1p5nUHf519XTmcoxJ2vrmiX+MMfrFEPZs8=
  app:
    master: moovin-hackathon-hw-vue
